Import('*')

# =========================
# Python SimObjects
# =========================
SimObject('UcieLink.py', sim_objects=['UcieLink'])
# =========================
# C++ Sources
# =========================
Source('ucie_link.cc')

# =========================
# Debug Flags (optional)
# =========================
DebugFlag('UcieLink')