# -------------------------------------------------------------------------
# test_ucie.py
# A basic testbench to verify the structural instantiation of the UCIeLink
# -------------------------------------------------------------------------

# Import the core gem5 simuation engine
import m5

# Import all compiled hardware models (SimObjects) dynamically generated by gem5.
from m5.objects import *

# =========================================================================
# 1. System & Clock Domain Setup
# =========================================================================
# The 'System' is the motherboard of the simulation. Every hardware component 
# must eventually be attached to a System object.
system = System()

# Hardware needs a clock and power to function.
# We create a clock domain running at 1 GHz and assign it a default voltage.
# By attaching this to 'system.clk_domain', every component we add to the system
# will automatically inherit this clock speed unless we specify otherwise.
system.clk_domain = SrcClockDomain(clock='1GHz', voltage_domain=VoltageDomain())

# =========================================================================
# 2. Instantiate the Hardware (Custom SimObjects)
# =========================================================================
# We are creating two instances of our custom UcieLink hardware.
# The parameters we pass here map directly to the Python configuration class
# we wrote (UcieLink.py), which then maps to the C++ variables in ucie_link.cc.
system.chiplet_A = UcieLink(link_latency='2ns', retry_buffer_capacity='32kiB', flit_size=256)
system.chiplet_B = UcieLink(link_latency='2ns', retry_buffer_capacity='32kiB', flit_size=256)

# =========================================================================
# 3. Wire the Hardware Together 
# =========================================================================
# gem5 uses port bindings to simulate physical wires.
# We connect the Transmit (Request) port of one chiplet to the Receive (Response)
# port of the other, establishing full-duplex, bidirectional communication.
system.chiplet_A.tx_port = system.chiplet_B.rx_port
system.chiplet_B.tx_port = system.chiplet_A.rx_port

# =========================================================================
# 4. Simulation Initialization
# =========================================================================
# The 'Root' is the absolute top of the gem5 simulation tree.
# full_system=False means we are running in System Emulation (SE) mode.
# which is a lightweight mode that doesn't require booting a full Linux OS kernel.
root = Root(full_system=False, system=system)

# m5.instantiate() is the magic command.
# It tells gem5 to stop reading Python, traverse the tree we just built, and
# physically allocate the C++ memory for all these objects and ports.
m5.instantiate()

# =========================================================================
# 5. Output Verification
# =========================================================================
# If the script reaches this point without crashing, the C++ backend has 
# successfully verified and instantiated all hardware.
print("====================================================")
print("SUCCESS: UcieLinks instantiated and ports connected!")
print(f"Chiplet A Flit Size: {system.chiplet_A.flit_size} Bytes")
print(f"Chiplet B latency: {system.chiplet_B.link_latency}")
print("====================================================")